-- PUBLIC.CLUB definition

-- Drop table

-- DROP TABLE PUBLIC.CLUB;

CREATE TABLE PUBLIC.CLUB (
	ID_CLUB INTEGER NOT NULL AUTO_INCREMENT,
	UBICACION CHARACTER VARYING(200) NOT NULL,
	NOMBRE CHARACTER VARYING(100) NOT NULL,
	TELEFONO INTEGER DEFAULT NULL,
	CONSTRAINT CONSTRAINT_1 PRIMARY KEY (ID_CLUB)
);
CREATE UNIQUE INDEX PRIMARY_KEY_1 ON PUBLIC.CLUB (ID_CLUB);



-- PUBLIC.HIBERNATE_SEQUENCE definition

-- Drop table

-- DROP TABLE PUBLIC.HIBERNATE_SEQUENCE;

CREATE TABLE PUBLIC.HIBERNATE_SEQUENCE (
	NEXT_VAL BIGINT DEFAULT NULL
);


-- PUBLIC.HISTORICO_RESERVAS definition

-- Drop table

-- DROP TABLE PUBLIC.HISTORICO_RESERVAS;

CREATE TABLE PUBLIC.HISTORICO_RESERVAS (
	ID_HISTORICO INTEGER NOT NULL AUTO_INCREMENT,
	ID_RESERVA INTEGER NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	ID_PISTA INTEGER NOT NULL,
	FECHA_RESERVA DATE NOT NULL,
	HORA_INICIO TIME NOT NULL,
	HORA_FIN TIME NOT NULL,
	ESTADO CHARACTER VARYING(20) NOT NULL,
	CONTADOR_MODIFICACIONES INTEGER DEFAULT NULL,
	FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT CONSTRAINT_A PRIMARY KEY (ID_HISTORICO)
);
CREATE INDEX HISTORICO_RESERVAS_FK_1_INDEX_A ON PUBLIC.HISTORICO_RESERVAS (ID_RESERVA);
CREATE INDEX HISTORICO_RESERVAS_FK_2_INDEX_A ON PUBLIC.HISTORICO_RESERVAS (ID_USUARIO);
CREATE INDEX HISTORICO_RESERVAS_FK_3_INDEX_A ON PUBLIC.HISTORICO_RESERVAS (ID_PISTA);
CREATE UNIQUE INDEX PRIMARY_KEY_A ON PUBLIC.HISTORICO_RESERVAS (ID_HISTORICO);

-- PUBLIC.HISTORICO_RESERVAS foreign keys

ALTER TABLE PUBLIC.HISTORICO_RESERVAS ADD CONSTRAINT FK21UWAQNMVUXR6359CCSMBS1IQ FOREIGN KEY (ID_RESERVA) REFERENCES PUBLIC.RESERVAS(ID_RESERVA) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE PUBLIC.HISTORICO_RESERVAS ADD CONSTRAINT FKLUUROD8VTTP7P0IU068A7GME5 FOREIGN KEY (ID_USUARIO) REFERENCES PUBLIC.USUARIOS(ID_USUARIO) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE PUBLIC.HISTORICO_RESERVAS ADD CONSTRAINT FKTMJWJO4E4TIK7VM99G79R8AG1 FOREIGN KEY (ID_PISTA) REFERENCES PUBLIC.PISTAS(ID_PISTA) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE PUBLIC.HISTORICO_RESERVAS ADD CONSTRAINT HISTORICO_RESERVAS_FK_1 FOREIGN KEY (ID_RESERVA) REFERENCES PUBLIC.RESERVAS(ID_RESERVA) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE PUBLIC.HISTORICO_RESERVAS ADD CONSTRAINT HISTORICO_RESERVAS_FK_2 FOREIGN KEY (ID_USUARIO) REFERENCES PUBLIC.USUARIOS(ID_USUARIO) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE PUBLIC.HISTORICO_RESERVAS ADD CONSTRAINT HISTORICO_RESERVAS_FK_3 FOREIGN KEY (ID_PISTA) REFERENCES PUBLIC.PISTAS(ID_PISTA) ON DELETE RESTRICT ON UPDATE RESTRICT;



-- PUBLIC.PISTAS definition
-- Drop table
-- DROP TABLE PUBLIC.PISTAS;

CREATE TABLE PUBLIC.PISTAS (
	ID_PISTA INTEGER NOT NULL AUTO_INCREMENT,
	NOMBRE_PISTA CHARACTER VARYING(50) NOT NULL,
	UBICACION CHARACTER VARYING(100) DEFAULT NULL,
	TIPO_PISTA CHARACTER VARYING(50) DEFAULT NULL,
	ID_CLUB INTEGER DEFAULT NULL,
	ESTADO CHARACTER VARYING(20) NOT NULL,
	FECHA_HORA CHARACTER VARYING(255) DEFAULT NULL,
	CONSTRAINT CONSTRAINT_8 PRIMARY KEY (ID_PISTA)
);
CREATE INDEX PISTAS_FK_1_INDEX_8 ON PUBLIC.PISTAS (ID_CLUB);
CREATE UNIQUE INDEX PRIMARY_KEY_8 ON PUBLIC.PISTAS (ID_PISTA);

-- PUBLIC.PISTAS foreign keys
ALTER TABLE PUBLIC.PISTAS ADD CONSTRAINT FKSM3GSP463FQ2YG71GN80U7QVF FOREIGN KEY (ID_CLUB) REFERENCES PUBLIC.CLUB(ID_CLUB) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE PUBLIC.PISTAS ADD CONSTRAINT PISTAS_FK_1 FOREIGN KEY (ID_CLUB) REFERENCES PUBLIC.CLUB(ID_CLUB) ON DELETE RESTRICT ON UPDATE RESTRICT;

---------------------------------------------------------------------
-- PUBLIC.RESERVAS definition

-- Drop table

-- DROP TABLE PUBLIC.RESERVAS;

CREATE TABLE PUBLIC.RESERVAS (
	ID_RESERVA INTEGER NOT NULL AUTO_INCREMENT,
	ID_USUARIO INTEGER NOT NULL,
	ID_PISTA INTEGER,
	FECHA_RESERVA DATE NOT NULL,
	HORA_INICIO TIME NOT NULL,
	HORA_FIN TIME NOT NULL,
	ESTADO CHARACTER VARYING(20) NOT NULL,
	CONTADOR_MODIFICACIONES INTEGER DEFAULT NULL,
	CONSTRAINT CONSTRAINT_19 PRIMARY KEY (ID_RESERVA)
);
CREATE UNIQUE INDEX PRIMARY_KEY_19 ON PUBLIC.RESERVAS (ID_RESERVA);
CREATE INDEX RESERVAS_FK_2_INDEX_1 ON PUBLIC.RESERVAS (ID_PISTA);


-- PUBLIC.RESERVAS foreign keys

ALTER TABLE PUBLIC.RESERVAS ADD CONSTRAINT RESERVAS_FK_3 FOREIGN KEY (ID_PISTA) REFERENCES PUBLIC.PISTAS(ID_PISTA) ON DELETE SET NULL ON UPDATE RESTRICT;

--------------------------------------------------------------------------

-- PUBLIC.TUTORIALS definition

-- Drop table

-- DROP TABLE PUBLIC.TUTORIALS;

CREATE TABLE PUBLIC.TUTORIALS (
	ID BIGINT NOT NULL,
	DESCRIPTION CHARACTER VARYING(255) DEFAULT NULL,
	PUBLISHED BOOLEAN DEFAULT NULL,
	TITLE CHARACTER VARYING(255) DEFAULT NULL,
	CONSTRAINT CONSTRAINT_B PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_B ON PUBLIC.TUTORIALS (ID);
----------------------------------------------------------------------
-- PUBLIC.USUARIOS definition

-- Drop table

-- DROP TABLE PUBLIC.USUARIOS;

CREATE TABLE PUBLIC.USUARIOS (
	ID_USUARIO INTEGER NOT NULL AUTO_INCREMENT,
	NOMBRE CHARACTER VARYING(50) NOT NULL,
	APELLIDOS CHARACTER VARYING(50) DEFAULT NULL,
	EMAIL CHARACTER VARYING(100) NOT NULL,
	TELEFONO CHARACTER VARYING(15) DEFAULT NULL,
	FECHA_REGISTRO DATE NOT NULL,
	CONTRASENA CHARACTER VARYING(255) NOT NULL,
	ROL CHARACTER VARYING(50) DEFAULT 'usuario' NOT NULL,
	CLUB CHARACTER VARYING(50),
	PISTAS CHARACTER VARYING(200),
	UBICACION CHARACTER VARYING(150),
	CONSTRAINT CONSTRAINT_3 PRIMARY KEY (ID_USUARIO),
	CONSTRAINT CONSTRAINT_39 UNIQUE (EMAIL)
);
CREATE UNIQUE INDEX CONSTRAINT_39_INDEX_C ON PUBLIC.USUARIOS (EMAIL);
CREATE UNIQUE INDEX PRIMARY_KEY_CC ON PUBLIC.USUARIOS (ID_USUARIO);













































