spring.h2.console.enabled=true
spring.datasource.url=jdbc:mysql://iestrassierra.net:3306/dawp2425a04?useSSL=false&serverTimezone=UTC
spring.datasource.username=dawp2425a04
spring.datasource.password=ZL_rokn2ShSS
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

